name: lib_sj
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ##网络请求
  dio: 5.0.3
  ##路由管理
  get: 4.6.5

  ##cookie管理
  dio_cookie_manager: 2.1.3
  dio_cache_interceptor: 3.4.0
  cookie_jar: 3.0.1

  ##toast提示框
  fluttertoast: ^8.2.1
  ##设备信息管理
  device_info_plus: ^8.2.2
  ##包体信息
  package_info_plus: ^3.0.3
  ##小数计算 https://github.com/a14n/dart-decimal
  decimal: 2.2.0
  ##本地存储
  shared_preferences: ^2.0.20
  ##多线程-锁/数据同步
  synchronized: ^3.0.0

  ##查找文件系统上常用位置
  path_provider: ^2.0.14
  ##图片加载
  cached_network_image: ^3.2.3
  ##下拉刷新
  pull_to_refresh: ^2.0.0
  ##加载框
  flutter_easyloading: 3.0.5
  ##日期格式化
  date_format: 2.0.7
  ##用于打开外部浏览器及应用
  url_launcher: ^6.1.10
  ##键盘
  keyboard_actions: ^4.2.0
  ##权限处理
  permission_handler: 10.2.0

  ##svg加载缓存
  flutter_svg: ^2.0.4
  ##luban使用
  image: ^4.0.17
  ##可以用来检查网络或者蓝牙连接状态
  connectivity_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  assets:
#    - assets/images
#    - assets/mimages/
#    - assets/mimages/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
